## Promise

> 자바스크립트에서 제공하는 비동기를 간편하게 처리할수 있도록 도와주는 오브젝트
>
> 정해진 장시간의 기능을 수행하고 나서 정상적으로 기능이 수행이 되어졌다면 성공 메시지와 처리된 값을 전달
>
> 예상치 못한 문제 발생하면 에러 전달

promise is a JavaScript object for asynchronous operation.

state: pending(오퍼레이션이 수행중일 때) -> fulfilled(오퍼레이션이 성공적으로 끝) or rejected (파일을 찾을 수 없거나 네트워크 문제가 생기면)

Producer(원하는 기능을 수행해서 해당하는 데이터를 만들어내는 : Promise object) vs Consumer(원하는 데이터를 소비하는)

```js
// 1. Producer
// when new Promise is created, the executor runs automatically.
// 불필요한 네트워크 연결 등을 수행할 수 있음
const promise = new Promise((resolve, reject) => {
    // doing some heavy work (network, read files...)
    console.log('doing something...');
    setTimeout(() => {
        resolve('ellie');
        // reject(new Error('no network'));
    }, 2000);
});

// 2. Consumers: then, catch, finally 를 이용해서 값을 받아올 수 있음
// then: 프로미스 기능이 원할히 이루어졌을 때
// catch: 오류 발생했을 때 에러메시지
// finally: 기능이 성공하던 실패하던 수행
promise
    .then((value) => {
        console.log(value);
    })
    .catch(error => {
        console.log(error);
    })
    .finally(() => {
        console.log('finally');
})

// 3. Promise chaining
const fetchNumber = new Promise((resolve, reject) => {
    setTimeout(() => resolve(1),1000);
});

fetchNumber
    .then(num => num * 2)
    .then(num => num * 3)
    .then(num => {
        return new Promise((resolve, reject) => {
            setTimeout(() => resolve(num-1),1000);
        })
    })
    .then(num => console.log(num));

// 4. Error Handling
const getHen = () =>
    new Promise((resolve, reject) => {
        setTimeout(() => resolve('🐓'), 1000);
    });
const getEgg = hen =>
    new Promise((resolve, reject) => {
        setTimeout(() => reject(new Error(`error! ${hen} => 🥚`), 1000));
    });
const cook = egg =>
    new Promise((resolve, reject) => {
        setTimeout(() => resolve(`${egg} => fried egg`), 1000);
    });

// getHen()
//     .then(getEgg) //.then(hen => getEgg(hen)) 
//                   //: 콜백함수를 정의할때 받아오는 밸류를 다른 함수로 바로 하나를 호출하는 경우 생갹가능
//     .then(cook) //then(egg => cook(egg))
//     .then(meal => console.log(meal));

getHen() //
.then(getEgg)
.catch(eroor => {
    return '빵';
})
.then(cook)
.then(console.log)
.catch(console.log);
```

